apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-api
  namespace: portfolio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - REPLACE_ME.duckdns.org
      secretName: portfolio-api-tls
  rules:
    - host: REPLACE_ME.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-api
                port:
                  number: 80
